apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helpdesk
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SaranyaDevi2005/helpdesk-devops
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: helpdesk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
